ELMA/Controllers/CandidateController.cs
using ELMA.DATA;
using ELMA.Models;
using ELMA.Models.Atributes;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ELMA.Controllers
{
    public class CandidateController : Controller
    {
        public static Logger logger = LogManager.GetCurrentClassLogger();
        public ActionResult Candidate()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Candidate(int candidateId)
        {
            logger.Info("Get candidate params");
            var candidate = (Candidate)DataModel.Repository.GetCandidateById(candidateId);
            var user = (User)DataModel.Repository.GetUserById(candidate.UserID);
            candidate.User = user;
            var workExperience = DataModel.Repository.GetWorkExperiencesByCandidateId(candidateId);
            var model = new CandidateModel()
            {
                Candidate = candidate,
                WorkExperiences = (List<WorkExperience>)workExperience
            };
            logger.Info("Open candidate view");
            return View(model);
        }

        [Authorize]
        public ActionResult Create(CandidateModel candidateModel,
                                    string addExperience,
                                    string deleteExperience,
                                    string createCandidate,
                                    HttpPostedFileBase image = null)
        {
            logger.Info("Start create new candidate");
            Models.Filter.ChangeCandidateExperience(ref candidateModel, addExperience, deleteExperience);

            if (createCandidate != null && ModelState.IsValid)
            {
                logger.Info("Create candidate if all params is Valid");
                if (image != null)
                {
                    logger.Info("Add image");
                    candidateModel.Candidate.ImageMimeType = image.ContentType;
                    candidateModel.Candidate.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(candidateModel.Candidate.ImageData, 0, image.ContentLength);
                    logger.Info("Create Candidate");
                    int candidate_id = DataModel.Repository.CreateCandidate(candidateModel.Candidate,  User.Identity.Name);
                    logger.Info("Create work experience for candidate");
                    DataModel.Repository.CreateWorkExperience(candidateModel.WorkExperiences, candidate_id);
                }
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }
                

            return View(candidateModel);
        }

        [Authorize]
        public FileContentResult GetImage(int candidate_id)
        {
            logger.Info("Get image");
            logger.Info("Get candidate by id");
            var candidate = (Candidate)DataModel.Repository.GetCandidateById(candidate_id);
            try
            {
                if (candidate != null)
                {
                    logger.Info("Return image file");
                    var ss = candidate.ImageData.ToString();
                    return File(candidate.ImageData, candidate.ImageMimeType);
                }
                else
                {
                    logger.Info("Candidate not found");
                    return null;
                }
            }
            catch(Exception ex)
            {
                logger.Error(ex.Message);
                return null;
            }
            
        }
        [Authorize]
        public ActionResult Close(int candidateId)
        {
            logger.Info("Close candidate");
            DataModel.Repository.DoUpdateActualyCandidate(candidateId);
            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }
    }
}

ELMA/Controllers/VacancyController.cs
using ELMA.DATA;
using ELMA.Models;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ELMA.Controllers
{
    public class VacancyController : Controller
    {
        public static Logger logger = LogManager.GetCurrentClassLogger();
        [Authorize]
        public ActionResult Vacancy()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Vacancy(int vacancyId)
        {
            logger.Info("Get params for vacancy");
            var model = (Vacancy)DataModel.Repository.GetVacancyById(vacancyId);
            var user = DataModel.Repository.GetUserById(model.UserID);
            model.User = (User)user;
            logger.Info("Show vacancy by id");
            return View(model);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        public ActionResult CreateVacancy(Vacancy vc)
        {
            logger.Info("Create vacancy");
            if(ModelState.IsValid)
            {
                DataModel.Repository.CreateVacancion(vc, User.Identity.Name);
                return RedirectToRoute(new { controller = "Home", action = "Candidates" });
            }
            return RedirectToAction("Create");
        }

        [Authorize]
        public ActionResult Close(int vacancyId)
        {
            logger.Info("Close vacancy");
            DataModel.Repository.DoUpdateActualyVacancy(vacancyId);
            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }
    }
}

ELMA/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/Home/Index">ELMA</a>
        <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarCollapse" 
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Candidates">Кандидаты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Vacancions">Вакансии</a>
                    </li>
                }

                @if (User.IsInRole("Jobseeker"))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Vacancions", "Home", new { userVacancy = true })">Мои вакансии</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Create", "Vacancy", new { userVacancy = true })">Создать вакансию</a>
                    </li>
                }
                @if (User.IsInRole("Employee"))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Candidates", "Home", new { userVacancy = true })">Мои резюме</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Create", "Candidate", new { userVacancy = true })">Создать резюме</a>
                    </li>
                }
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                <a href="/Autorization/LogOut" class="btn btn-success ml-1 my-2 my-sm-0" type="submit">LogOut</a>
            </form>
        </div>
    </nav>
</header>

ELMA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
 
    @RenderBody()


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquerymask")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/filter")
    @RenderSection("scripts", required: false)
</body>
</html>